# 生产环境配置

# 数据源配置
spring:
  #redis 配置
  redis:
    host: 192.168.0.13
    port: 6379
    password: i-search@2019
    jedis:
      pool:
        max-active: 8 # 连接词最大链接数
        max-wait: -1 # 连接池最大阻塞等待时间（负数代表没有限制）
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        timeout: 10000 # 链接超时时间 （ms）,连接时间小会导致连接超时
    # 生产环境配置
    # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/i_cas?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
