server:
  port: 8000

spring:
  application:
    name: boot-cli
  profiles:
    active: dev
  # 模板引擎配置
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true


#mybatis:
#  type-aliases-package: com.isearch.oauth2.model
#  mapper-locations: classpath:/mapper/*.xml # mapper 文件路径
##通用mapper
#mapper:
#  mappers:
#    - com.isearch.common.base.mapper.BaseMapper
#  not-empty: false
#  identity: MYSQL
##分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml # mapper 文件路径
  type-aliases-package: com.isearch.oauth2.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid
      db-type: mysql  # 3.0 版本的必须配置 不然无法启动 nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:java.lang.NullPointerException



